/* AUTO-GENERATED by tools/cxnc — do not edit */
#include "pages.h"

void app_layout(HttpRequest *req, PageCtx *ctx, PageFn child) {
    (void)req;
    page_write(ctx, "<!DOCTYPE html>\n");
    page_write(ctx, "<html lang=\"en\">\n");
    page_write(ctx, "<head>\n");
    page_write(ctx, "  <meta charset=\"UTF-8\">\n");
    page_write(ctx, "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    page_write(ctx, "  <title>cnext</title>\n");
    page_write(ctx, "  <link rel=\"stylesheet\" href=\"/style.css\">\n");
    page_write(ctx, "</head>\n");
    page_write(ctx, "<body>\n");
    page_write(ctx, "  <nav class=\"navbar\">\n");
    page_write(ctx, "    <a href=\"/\" class=\"logo\">cnext</a>\n");
    page_write(ctx, "  </nav>\n");
    page_write(ctx, "  <main>\n");
    if (child) child(req, ctx);
    page_write(ctx, "\n");
    page_write(ctx, "  </main>\n");
    page_write(ctx, "  <footer class=\"footer\">\n");
    page_write(ctx, "    <p>Powered by <strong>C + io_uring</strong> &mdash; SSR like Next.js</p>\n");
    page_write(ctx, "  </footer>\n");
    page_write(ctx, "</body>\n");
    page_write(ctx, "</html>\n");
}

